### ISSUE TITLE
Yuan-2.0 2.1B模型在进行模型微调的时候报显存容量不足的问题

### ISSUE THREAD

**Issue by fredfany** [IEIT-Yuan/Yuan-2.0#87]
环境：
```
[root@XXX Yuan-2.0]# nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P4                       Off | 00000000:04:00.0 Off |                    0 |
| N/A   36C    P8               7W /  75W |      4MiB /  7680MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4007      G   /usr/libexec/Xorg                             4MiB |
+---------------------------------------------------------------------------------------+
```
 执行命令：
`bash +x examples/pretrain_yuan2.0_2.1B_sft.sh`

错误打印：
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.78 GiB. GPU 0 has a total capacty of 7.43 GiB of which 3.19 GiB is free. Including non-PyTorch memory, this process has 4.23 GiB memory in use. Of the allocated memory 3.89 GiB is allocated by PyTorch, and 101.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

所采取的措施：
修改 examples/pretrain_yuan2.0_2.1B_sft.sh中可能跟内容有关的参数
```
 DISTRIBUTED_ARGS="
     --nproc_per_node $GPUS_PER_NODE \
@@ -29,9 +30,9 @@ GPT_ARGS="
     --tensor-model-parallel-size 1 \
     --pipeline-model-parallel-size 1 \
     --timing-log-level 2 \
-    --num-workers 2 \
-    --num-layers 24 \
-    --hidden-size 2048 \
+    --num-workers 1 \
+    --num-layers  12\
+    --hidden-size 1024 \
     --num-attention-heads 32 \
     --use-lf-gate \
     --lf-conv2d-group 1 \
@@ -52,8 +53,8 @@ GPT_ARGS="
     --adam-beta2 0.95 \
     --seq-length 8192 \

```
诉求：有没有办法通过修改代码，让8GB内存的显卡也能进行模型微调测试，对物理资源限制过高影响到该模型的推广应用

**Comment by zhuhong** [comment]
https://github.com/IEIT-Yuan/Yuan-2.0/blob/main/docs/Yuan2_llama-factory.md ; 可以参考这个教程使用LoRA或者QLoRA进行微调

**Comment by fredfany** [comment]
感谢回复！麻烦再问一下，我用hugingface 2.1B模型进行推理时，提示FlashAttention不支持我的显卡（Tesla P4），目前手头就这块卡，就想用这块卡快速做一下Yuan模型的推理、微调等，看看有没有什么简单的办法，谢谢！

2 FlashAttention only supports Ampere GPUs or newer.

**Comment by zhaoxudong01** [comment]
可以在config文件中关闭flash attention的使用，精度结果会略有差别

**Comment by fredfany** [comment]
可以工作了，多谢！

**Comment by fredfany** [comment]
按照这个流程搞了半天，还是报“CUDA out of memory.”，打印如下，我的卡是Tesla P4 8GB，请问还有什么办法（比如改代码等）能跑微调
```
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/yuan_hf_model.py", line 366, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacty of 7.43 GiB of which 995.62 MiB is free. Process 691814 has 6.45 GiB memory in use. Of the allocated memory 6.10 GiB is allocated by PyTorch, and 94.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                                                                                            | 0/327 [00:02<?, ?it/s]
[2024-01-12 09:44:59,048] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2535
[2024-01-12 09:44:59,048] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python', '-u', 'src/train_bash.py', '--local_rank=0', '--stage', 'sft', '--model_name_or_path', '/workspace/model_file/YuanLLM_Yuan2-2B-hf/', '--do_train', '--dataset', 'alpaca_zh', '--finetuning_type', 'lora', '--output_dir', '/workspace/workspace/yuan2_2B_full_fintuning_checkpoint/', '--overwrite_cache', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '4', '--preprocessing_num_workers', '16', '--lr_scheduler_type', 'cosine', '--logging_steps', '10', '--save_steps', '10000', '--learning_rate', '5e-5', '--max_grad_norm', '0.5', '--num_train_epochs', '3', '--evaluation_strategy', 'no', '--fp16', '--template', 'yuan', '--overwrite_output_dir', '--cutoff_len', '2048', '--sft_packing', '--gradient_checkpointing', 'True', '--quantization_bit', '4', '--lora_target', 'q_proj'] exits with return code = 1
```

**Comment by fredfany** [comment]
我使用的命令如下：
```

deepspeed --num_gpus=1 src/train_bash.py \
        --stage sft \
        --model_name_or_path /workspace/model_file/YuanLLM_Yuan2-2B-hf/  \
        --do_train \
        --dataset alpaca_zh \
        --finetuning_type lora \
        --output_dir /workspace/workspace/yuan2_2B_full_fintuning_checkpoint/ \
        --overwrite_cache \
        --per_device_train_batch_size 4 \
        --per_device_eval_batch_size 4  \
        --gradient_accumulation_steps 4  \
        --preprocessing_num_workers 16 \
        --lr_scheduler_type cosine \
        --logging_steps 10    \
        --save_steps 10000   \
        --learning_rate 5e-5   \
        --max_grad_norm 0.5     \
        --num_train_epochs 3   \
        --evaluation_strategy no  \
        --fp16 \
        --template yuan \
        --overwrite_output_dir     \
        --cutoff_len 2048\
        --sft_packing   \
        --gradient_checkpointing True \
        --quantization_bit 4 \
		--lora_target q_proj

```

**Comment by zhuhong** [comment]
bs设成1试试

**Comment by fredfany** [comment]
出现下面的打印是否意味着训练开始了~~
```
[INFO|trainer.py:1706] 2024-01-12 10:34:52,530 >> ***** Running training *****
[INFO|trainer.py:1707] 2024-01-12 10:34:52,530 >>   Num examples = 1,741
[INFO|trainer.py:1708] 2024-01-12 10:34:52,530 >>   Num Epochs = 3
[INFO|trainer.py:1709] 2024-01-12 10:34:52,530 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1712] 2024-01-12 10:34:52,530 >>   Total train batch size (w. parallel, distributed & accumulation) = 4
[INFO|trainer.py:1713] 2024-01-12 10:34:52,530 >>   Gradient Accumulation steps = 4
[INFO|trainer.py:1714] 2024-01-12 10:34:52,530 >>   Total optimization steps = 1,305
[INFO|trainer.py:1715] 2024-01-12 10:34:52,533 >>   Number of trainable parameters = 786,432
  0%|                                                                                                                                                           | 0/1305 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:418: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
  0%|                                                                                                                                                | 1/1305 [00:51<18:35:05, 51.31s/it]
```

**Comment by fredfany** [comment]
麻烦再问一下，我按如上方法，把微调完成之后的结果导出（[export_model.py](https://github.com/hiyouga/LLaMA-Factory/blob/main/src/export_model.py)），形成新的模型参数，然后使用新的模型参数进行推理，结果反不如以前，连原来可以正常推导的问题也失败了，结果如下，这个可能是什么原因，该如何处理
```
nk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><un
172.17.0.2 - - [14/Jan/2024 13:57:56] "PUT /yuan HTTP/1.1" 200 -
```

**Comment by wangpengfei1013** [comment]
> 麻烦再问一下，我按如上方法，把微调完成之后的结果导出（[export_model.py](https://github.com/hiyouga/LLaMA-Factory/blob/main/src/export_model.py)），形成新的模型参数，然后使用新的模型参数进行推理，结果反不如以前，连原来可以正常推导的问题也失败了，结果如下，这个可能是什么原因，该如何处理
> 
> ```
> nk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><un
> 172.17.0.2 - - [14/Jan/2024 13:57:56] "PUT /yuan HTTP/1.1" 200 -
> ```

（1）建议使用中文指令数据集对yuan2.0进行微调；
（2）可以尝试增大global-bs看一下效果，即调大这个--gradient_accumulation_steps 4 这个参数
（3）使用bf16

**Comment by fredfany** [comment]
我用LLaMa训练hugingface 2.1B模型，按照上述建议，调整了一下训练的参数如下，我构造了一个包含225条用例的数据集，其中2条是自拟的，其他是从data/oaast_rm_zh.json这个数据集中摘取的，我希望我自拟的2条能够生效（基本安装我的提问来回答），以下训练了30轮，学习率为5e-5，训练完成结果导出之后发现没有奏效，表现为我的提问没有得到想要的回答。

想了解下，这个原因可能是什么，有没有办法让训练灌入的数据集能快速生效。

```
	deepspeed --num_gpus=1 src/train_bash.py \
        --stage sft \
        --model_name_or_path /workspace/model_file/YuanLLM_Yuan2-2B-hf/  \
        --do_train \
        --dataset custom1 \
        --finetuning_type lora \
        --output_dir /workspace/workspace/yuan2_2B_lora_fintuning_checkpoint1/ \
        --overwrite_cache \
        --per_device_train_batch_size 1 \
        --per_device_eval_batch_size 4  \
        --gradient_accumulation_steps 4  \
        --preprocessing_num_workers 16 \
        --lr_scheduler_type cosine \
        --logging_steps 10    \
        --save_steps 10000   \
        --learning_rate 5e-5   \
        --max_grad_norm 0.5     \
        --num_train_epochs 10   \
        --evaluation_strategy no  \
        --fp16 \
        --template yuan \
        --overwrite_output_dir     \
        --cutoff_len 2048\
        --sft_packing   \
        --gradient_checkpointing True \
       --quantization_bit 4 \
	 --lora_target q_proj
```

**Comment by wangpengfei1013** [comment]
> 我用LLaMa训练hugingface 2.1B模型，按照上述建议，调整了一下训练的参数如下，我构造了一个包含225条用例的数据集，其中2条是自拟的，其他是从data/oaast_rm_zh.json这个数据集中摘取的，我希望我自拟的2条能够生效（基本安装我的提问来回答），以下训练了30轮，学习率为5e-5，训练完成结果导出之后发现没有奏效，表现为我的提问没有得到想要的回答。
> 
> 想了解下，这个原因可能是什么，有没有办法让训练灌入的数据集能快速生效。
> 
> ```
> 	deepspeed --num_gpus=1 src/train_bash.py \
>         --stage sft \
>         --model_name_or_path /workspace/model_file/YuanLLM_Yuan2-2B-hf/  \
>         --do_train \
>         --dataset custom1 \
>         --finetuning_type lora \
>         --output_dir /workspace/workspace/yuan2_2B_lora_fintuning_checkpoint1/ \
>         --overwrite_cache \
>         --per_device_train_batch_size 1 \
>         --per_device_eval_batch_size 4  \
>         --gradient_accumulation_steps 4  \
>         --preprocessing_num_workers 16 \
>         --lr_scheduler_type cosine \
>         --logging_steps 10    \
>         --save_steps 10000   \
>         --learning_rate 5e-5   \
>         --max_grad_norm 0.5     \
>         --num_train_epochs 10   \
>         --evaluation_strategy no  \
>         --fp16 \
>         --template yuan \
>         --overwrite_output_dir     \
>         --cutoff_len 2048\
>         --sft_packing   \
>         --gradient_checkpointing True \
>        --quantization_bit 4 \
> 	   --lora_target q_proj
> ```

以下几个方面还请考虑：
（1）lora-target 尝试多加如几个模块，一般qlora 是所有可加入层都加
（2）调低以下学习率
（3）更多epoch让数据过拟合，即loss接近0或为0试一下
（4）推理时注意 温度 topk等参数设置，建议参照 https://zhuanlan.zhihu.com/p/653926703来做尝试

**Comment by fredfany** [comment]
按照上面的建议，调整了lora-target的模块为'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj'，增大了学习率为  --learning_rate 5e-3 （原来是5e-5），还是没有看到训练的效果，例如我在数据集里加一条用例
    "instruction": "请问XXX大学现任校长是谁？",
    "input": "",
    "output": "吴XX."
我希望训练（参数微调）完成后按照这个提问的话，新模型能按这个告诉我，实际上没有

另一个问题，我从原始的模型开始，增加预训练数据集1，导出得到模型1，如果我要再增加训练数据2，是不是要在模型1的基础上进行，得到模型2，依次类推，每次训练都要更换模型基线，否则原来训练的效果保留不下来

```
deepspeed --num_gpus=1 src/train_bash.py \
        --stage sft \
        --model_name_or_path /workspace/model_file/YuanLLM_Yuan2-2B-hf/  \
        --do_train \
        --dataset custom1 \
        --finetuning_type lora \
        --output_dir /workspace/workspace/yuan2_2B_lora_fintuning_checkpoint2/ \
        --overwrite_cache \
        --per_device_train_batch_size 1 \
        --per_device_eval_batch_size 4  \
        --gradient_accumulation_steps 4  \
        --preprocessing_num_workers 16 \
        --lr_scheduler_type cosine \
        --logging_steps 10    \
        --save_steps 10000   \
        --learning_rate 5e-3   \
        --max_grad_norm 0.5     \
        --num_train_epochs 10   \
        --evaluation_strategy no  \
        --fp16 \
        --template yuan \
        --overwrite_output_dir     \
        --cutoff_len 2048\
        --sft_packing   \
        --gradient_checkpointing True \
       --quantization_bit 4 \
	 --lora_target 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj'
```

**Comment by wangpengfei1013** [comment]
> 按照上面的建议，调整了lora-target的模块为'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj'，增大了学习率为 --learning_rate 5e-3 （原来是5e-5），还是没有看到训练的效果，例如我在数据集里加一条用例 "instruction": "请问XXX大学现任校长是谁？", "input": "", "output": "吴XX." 我希望训练（参数微调）完成后按照这个提问的话，新模型能按这个告诉我，实际上没有

学习率调小，不是调大哦
完成微调后，可以使用如下脚本去测试下。
import torch, transformers
import sys, os
import argparse
#sys.path.append(
#            os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
from transformers import AutoModelForCausalLM,AutoTokenizer,LlamaTokenizer

parser=argparse.ArgumentParser(description="paramter you should add")
parser.add_argument('-m','--model',type=str,default='./yuan2_2B_test_full_fintuning_checkpoint',help='specipy model file ')
parser.add_argument('--use_peft',default=False,action='store_true',help='using peft model inference')
parser.add_argument('--print_arch',default=False,action='store_true',help='using print(model)')
parser.add_argument('--summary_arch',default=False,action='store_true',help='using summary(model)')
parser.add_argument('-p',"--peft",type=str,default='./yuan2_2B_test_full_fintuning_checkpoint',help='peft model path')
args=parser.parse_args()


print("Creat tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(args.model,padding_side='left')
#tokenizer = LlamaTokenizer.from_pretrained(args.model,padding_side='left',add_bos_token=False,add_eos_token=False,eos_token='<eod>')
#tokenizer.padding_side = "left"

tokenizer.add_tokens(['<sep>', '<pad>', '<mask>', '<predict>', '<FIM_SUFFIX>', '<FIM_PREFIX>', '<FIM_MIDDLE>','<commit_before>','<commit_msg>','<commit_after>','<jupyter_start>','<jupyter_text>','<jupyter_code>','<jupyter_output>','<empty_output>'], special_tokens=True)

print("Creat model...")
model = AutoModelForCausalLM.from_pretrained(args.model,device_map='auto',torch_dtype=torch.bfloat16,trust_remote_code=True)
if args.print_arch:
    print("model arch...\n")
    print(model)
if args.summary_arch:
    from torchsummary import summary
    a=torch.randint(1,100000,(1,30)).to("cuda:0")
    summary(model.to("cuda:0"),a)
if args.use_peft:

    from peft import PeftModel
    model=PeftModel.from_pretrained(model,args.peft,torch_dtype=torch.bfloat16,device_map='auto')
model.eval()

question=["妈妈买了4个蛋糕，每个蛋糕7元，30元钱够吗?<sep>","地三鲜的做法<sep>"]
for i in range(len(question)):


    inputs = tokenizer(question[i], return_tensors="pt")["input_ids"].to("cuda:0")
    #print("wpf input size: ",inputs.size())
#print(inputs)
#input_ids = inputs["input_ids"].to("cuda:0")
    with torch.no_grad():
        outputs = model.generate(input_ids=inputs,output_scores=True,max_length=512,top_k=1,do_sample=False)

    print("input_len: ",inputs.size()[1],"output_len: ",outputs[0].size()[0]-inputs.size()[1],tokenizer.decode(outputs[0]))
 
 另一个问题，我从原始的模型开始，增加预训练数据集1，导出得到模型1，如果我要再增加训练数据2，是不是要在模型1的基础上进行，得到模型2，依次类推，每次训练都要更换模型基线，否则原来训练的效果保留不下来
是的

**Comment by fredfany** [comment]
学习率调小，改成--learning_rate 5e-6 （原来是5e-5），并且自己杜撰了几条崭新的信息进去，好像也不行。因为是新手，所以单纯的想法就是如果自己新加入的信息能别推理出来，就证明训练成功了，这个来的最直接，有没有办法能做到这一点，谢谢

**Comment by fredfany** [comment]
后面发现，还是训练的轮次不够，使用了8卡A800跑3000轮之后，数据就可以学习到了

**Comment by wangpengfei1013** [comment]
OK，我之前用self-configtion数据（llama-factory提供的）微调模型是能学习到的。 此issue若暂无问题 可以先关闭 @fredfany

**Comment by fredfany** [comment]
收到，非常感谢！
